platform :ios, '15.0'
use_frameworks!

target 'GodotxFirebaseRemoteConfig' do
  pod 'Firebase/RemoteConfig', '12.7.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end
end
